<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Epixa Cards Prototype</title>

    <link rel="stylesheet" href="/css/screen.css" type="text/css" media="screen" />

    <script src="/js/jquery-1.6.1.min.js" type="text/javascript"></script>
    <script src="/js/chain.js" type="text/javascript"></script>
    <script src="/js/global.js" type="text/javascript"></script>
    <script src="/js/game.js" type="text/javascript"></script>
    <script src="/js/game.river.js" type="text/javascript"></script>
    <script type="text/javascript">
        var room = new game.Room('/ajax.php?action=get-game');
    </script>
</head>
<body>
    <?php require 'partials/header.phtml'; ?>

    <section id="room">
        <?php
            if ($game) {
                require 'partials/game.phtml';
            } else {
                require 'partials/no-game.phtml';
            }
        ?>
    </section>

    <script type="text/javascript">
        (function($){
            //room.beginPolling();
            //var room = game.roomFactory($('#room'), $('#table'), $('#players'));
            //room.startGame(new game.river.Game());

            /*$('#players')
                .item({
                    player: 'Court'
                })
                .chain({
                    '.player': {
                        id: 'player-1'
                    }
                });*/
        })(jQuery);
    </script>
</body>
</html>