
<h1>Playing: <?php echo htmlentities($game->name); ?></h1>
<div>Total players: <span id="total-players"><?php echo (int)$totalPlayers; ?></span></div>
<a id="stop-game" href="#stop-game">Stop Game</a>

<section id="table"></section>
<ul id="players">
    <li id="player-base"></li>
</ul>


<script type="text/javascript">
(function(){
    $('#stop-game').click(function(e){
        e.preventDefault();

        if (confirm("Are you sure you want to stop the current game?")) {
            $.post('/ajax.php?action=stop-game', function(data){
                if (data.status == 'error') {
                    $(document).trigger('ajax.error', [data]);
                } else if (data.status == 'success') {
                    window.location.href = '/';
                }
            }, 'json');
        }
    });

    var originalCallback = room.loadGameDataCallback;
    room.loadGameDataCallback = function(data){
        if (!data.game) {
            alert('Someone has stopped the current game');
            window.location.href = '/';
        } else {
            var microtime = new Date().getTime() / 1000;

            for (var x in data.game.players) {
                if (!data.game.players[x].isActive) {
                    console.log(data.game.players[x].name + ' is not active');
                }
            }

            $('#total-players').html(data.game.totalPlayers);
            
            originalCallback(data);
        }
    };
    room.beginPolling();
})();
</script>