
<section>
    <h1>No game is currently being played</h1>

    <p>Anyone can start a new game, however.  So, what are you waiting for?</p>

    <a id="start-game" href="#start-game">Start Game</a>
</section>

<script type="text/javascript">
    (function(){
        $('#start-game').click(function(e){
            e.preventDefault();

            manager.startGame();
        });

        manager.pollGameStarted();
    })();
</script>
