
<section>
    <h1>No game is currently being played</h1>

    <p>Anyone can start a new game, however.  So, what are you waiting for?</p>

    <a id="start-game" href="#start-game">Start Game</a>
</section>

<script type="text/javascript">
    (function(){
        $('#start-game').click(function(e){
            e.preventDefault();

            $.post('/ajax.php?action=start-game', function(data){
                if (data.status == 'error') {
                    $(document).trigger('ajax.error', [data]);
                } else if (data.status == 'success') {
                    window.location.href = '/';
                }
            }, 'json');
        });

        $(document).bind('game.Manager.gameStarted', function(event, game){
            alert("Someone has started a new game:\n" + game.details.name);
            window.location.href = '/';
        });

        manager.pollGameStarted('/ajax.php?action=get-game');
    })();
</script>
